name: Build GH Action
on:
  push:
    branches:
      - ino_dev
jobs:
  BuildTestDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build & test with Maven
        run: mvn --batch-mode package

      - name: Deploy
        run: java -jar target/EmployeeResolver-1.jar  sampleFiles/employees.csv
